CREATE TABLE ROLE(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(20),
	PRIMARY KEY(ID)
)

CREATE TABLE USER_ROLE(
	user_id INT,
	role_id INT,
	FOREIGN KEY(user_id) REFERENCES USER(id),
	FOREIGN KEY(role_id) REFERENCES role(id)
)

INSERT INTO role VALUES(1,'ADMIN')

INSERT INTO USER_ROLE VALUES(1,1)

